[package]
name = "panicatorul"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm-sys = { version = "170" } #, features = ["force-dynamic"] }
smallstr = "0.3.0"
clap = { version = "4", features = ["derive"] }
